setting = {
    "index" : {
    'school_name': 0,
    'year': 1,
    'StudentID': 2,
    'First Name': 3,
    'Last Name': 4,
    'Year Level': 5,
    'Class': 6,
    'Subject': 7,
    'Answers': 8,
    'Correct Answers': 9,
    'Question Number': 10,
    'Subject Contents': 11,
    'Assessment Areas': 12,
    'sydney_correct_count_percentage': 13,
    'sydney_average_score': 14,
    'sydney_participants': 15,
    'student_score': 16,
    'student_total_assessed': 17,
    'student_area_assessed_score': 18,
    'total_area_assessed_score': 19,
    'participant': 20,
    'correct_answer_percentage_per_class': 21,
    'average_score': 22,
    'school_percentile': 23,
    'sydney_percentile': 24,
    'strength_status': 25,
    'high_distinct_count': 26,
    'distinct_count': 27,
    'credit_count': 28,
    'participant_count': 29,
    'award': 30
},
}